config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  get "dashboard", to: "pages#dashboard"
  get "search", to: 'pages#search'
  get "books/:id", to: 'pages#books'
  get "lists", to: "lists#index"
  get "lists/new", to: "lists#new", as: "new_list"
  post "lists", to: "lists#create"
  patch "user/:id", to: "users#update", as: 'username_edit'
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :books, through: :book_list
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @user = current_user
    @lists = List.where(user: @user)
  end

  def new
    @list = List.new
  end
  
  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  private

  def list_params
    params.require(:list).permit(:name).merge(user_id: current_user.id)
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/index.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<%= link_to 'New List', new_list_path %>
<% @lists.each do |list| %>
  <%= list.name %>
<% end %>

app/views/lists/new.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<%= form_for(@list) do |form|%>
  <%= form.text_field :name %>
  <%= form.submit "Create List" %>
<% end %>