config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  get "dashboard", to: "pages#dashboard"
  get "search", to: 'pages#search'
  get "books/:id", to: 'pages#books'
  get "lists", to: "lists#index"
  get "lists/new", to: "lists#new", as: "new_list"
  post "lists", to: "lists#create"
  patch "user/:id", to: "users#update", as: 'username_edit'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  has_many :publishers, through: :books
  has_many :collections, through: :books
end

app/models/bibili.rb
class Bibili < ApplicationRecord
  belongs_to :user
  has_many :book
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :lists, through: :book_list
end

app/models/book_list.rb
class BookList < ApplicationRecord
  belongs_to :list, foreign_key: "list_id"
  belongs_to :book, foreign_key: "book_id"
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_many :books
  has_many :authors, through: :books
  belongs_to :publisher
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :books, through: :book_list
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books
  has_many :collections
  has_many :authors, through: :books
end

app/models/reading.rb
class Reading < ApplicationRecord
  has_one :book, foreign_key: "book_id"
  belongs_to :user, foreign_key: "user_id"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable
  has_many :readings
  has_many :lists
  has_many :books, through: :readings
  has_many :books, through: :whishlists

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @user = current_user
    @lists = List.where(user: @user)
  end

  def new
    @list = List.new
  end
  
  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  private

  def list_params
    params.require(:list).permit(:name).merge(user_id: current_user.id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
    if user_signed_in?
      @user = current_user
      render 'pages/dashboard'
    else
      redirect_to root_path
    end
  end

  def search
    @query = params[:query]
  end

  def books
    @id = params[:id]
  end
end

app/controllers/readings_controller.rb
class ReadingsController < ActionController::Base
  before_action :authenticate_user!

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def update
  end

  def destroy
  end

  private

  def reading_params
  end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base

  def update
    @user = User.find(params[:id])
    last_updated = @user.updated_at.to_date
    today = Date.today
    if (today - last_updated).to_i > 29
      @user.update(username: params[:user]["username"])
    else
      redirect_to dashboard_path
      flash.alert = 'Dernière mise à jour il y a moins de 30 jours'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bibili</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Grand+Hotel&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="">
    <% if user_signed_in? %>
      <%= render 'shared/nav-signed-in' %>
    <% else %>
      <%= render 'shared/nav' %>
    <% end %>


    <%= yield %>

    <%# <%= render 'shared/footer' %> 
  </body>

</html>

app/views/pages/books.html.erb
<br>
<br>
<br>
<br>
<div class="book-info-container"></div>

app/views/pages/dashboard.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<% flash.each do |type, msg| %>
    <p><%= msg %></p>
<% end %>
<%= form_for(:user, url: username_edit_path(@user), method: "patch") do |form|%>
  <%= form.text_field :username %>
  <%= form.submit "Update" %>
<% end %>

app/views/pages/home.html.erb
<div class="acc h-screen w-screen bg-green-50 flex items-center justify-center">
  <h1>accueil</h1>
</div>

app/views/pages/search.html.erb
<br>
<br>
<br>
<br>
<button class="titles-filter">Titres</button>
<button class="authors-filter">Authors</button>
<br>
<div class="fetched-content"></div>

app/views/shared/_nav-signed-in.html.erb
<nav class="shadow-md bg-green-50 text-pink-900 fixed w-screen">
  <div class="container flex max-w-screen-xl m-auto justify-between px-5 items-center">
    
    <div class="logo-content">
      <%= link_to root_path do %>
        <p class="logo logo-up leading-10 py-1 mt-2" href="#">Bibili</p>
      <% end %>
    </div>

    <div class="search w-1/3 shadow-inner">
      <form class="searchbar bg-white flex items-center w-full">
        <i class="fas fa-search"></i>
        <input id="keyword" name="Search" type="text" class="form-control py-1 pr-2 pl-10 w-full" placeholder="Titre, auteur, isbn...">
        <input type="submit" value="Search" style="visibility: hidden;" tabindex="-1" />
      </form>
  
    </div>

    <div class="sign flex items-center h-full">

      <div class="nav-profil flex items-center">
        <i class="far fa-user-circle mr-2.5"></i>
      </div>
      <div class="sign-up px-2.5 hover:bg-green-200 flex items-center">
        <%= link_to destroy_user_session_path, :method => :delete, :class=> "font-medium" do %>
          <p>Se déconnecter</p>
        <% end %>
      </div>

    </div>

  </div>
</nav>

app/views/shared/_nav.html.erb
<nav class="shadow-md bg-green-50 text-pink-900 fixed w-screen">
  <div class="container flex max-w-screen-xl m-auto justify-between px-5 items-center">
    
    <div class="logo-content">
      <%= link_to root_path do %>
        <p class="logo logo-up leading-10 py-1 mt-2" href="#">Bibili</p>
      <% end %>
    </div>

    <div class="search w-1/3 shadow-inner">
      <form class="searchbar bg-white flex items-center w-full" action="/search/">
        <i class="fas fa-search"></i>
        <input id="keyword" name="books" type="text" class="form-control py-1 pr-2 pl-10 w-full" placeholder="Titre, auteur, isbn...">
        <input type="submit" style="visibility: hidden;" tabindex="-1" />
      </form>
  
    </div>

    <div class="sign flex items-center h-full">

      <div class="nav-profil flex items-center">
        <i class="far fa-user-circle mr-2.5"></i>
      </div>
      <div class="sign-in mr-2.5 px-2.5 hover:bg-green-200 flex items-center">
        <%= link_to user_session_path, :class=> "font-medium" do%>
          <p>Se connecter</p>
        <% end %>
      </div>
      <div class="sign-up px-2.5 hover:bg-green-200 flex items-center">
        <%= link_to new_user_registration_path, :class=> "font-medium" do %>
          <p>S'inscrire</p>
        <% end %>
      </div>

    </div>

  </div>
</nav>